### ISSUE TITLE
3 - Investigate Bitmap generation performance

### ISSUE THREAD

**Issue by maczech** [GerritForge/gerritforge-health-service#43] opened 2024-03-15 15:34 UTC

**Comment by DanieleSassoli** [comment] 2024-03-27 11:01
+1

**Comment by dzsessona** [comment] 2024-03-27 11:03
+1

**Comment by dluksza** [comment] 2024-03-27 11:03
+1

**Comment by syntonyze** [comment] 2024-04-15 14:10
I have taken the ghs-gym tarball from review-4 (`20240314.144600.ghs-gym.git.tar.gz`)

```
➜  pack git:(master) ls -1 *.bitmap | wc -l
       5
➜  pack git:(master) ls -1 *.pack | wc -l
    7731
```

I have then triggered the executor (with a textual progress monitor to have a better understanding of the different phases):

```
time java -jar target/actions-executor-1.0-SNAPSHOT-jar-with-dependencies.jar BitmapGenerationAction ~/ghs/ghs-gym.git

Counting objects:       497195
Finding sources:        100% (497195/497195)
Getting sizes:          100% (180552/180552)
Compressing objects:    100% (4409288/4409288)
Writing objects:        100% (497195/497195)
Selecting commits:      153459
Selecting commits:      100% (153459/153459)
Building bitmaps:       100% (30029/30029)

153.03s user 5.27s system 110% cpu 2:23.02 total
```

You can see how the entire operation took 2 minutes and 23 seconds.
Most of the time was spent in the `Finding sources` phase, which has to scan 7731 packfiles to find the best object representation.

At the end of the action, as expected, 1 new packfile was created alongside 1 bitmap.

```
➜  pack git:(master) ls -1 *.pack | wc -l
    7732
➜  pack git:(master) ls -1 *.bitmap | wc -l
       6
```

Since the pruning phase was not executed (this is not a GC action), the number of packfiles thus was not reduced.

This means that a subsequent run of the same action shows a further decrease of performance (3 minutes and 18 seconds).
This is expected because the number of packfiles now is even higher, since it is inclusive of the repacked heads-and-tags packfile.

```
time java -jar target/actions-executor-1.0-SNAPSHOT-jar-with-dependencies.jar BitmapGenerationAction ~/ghs/ghs-gym.git

Counting objects:       497195
Finding sources:        100% (497195/497195)
Getting sizes:          100% (180552/180552)
Writing objects:        100% (497195/497195)
Selecting commits:      153459
Selecting commits:      100% (153459/153459)
Building bitmaps:       100% (30029/30029)
1713181072119: Done packs with bitmap

201.24s user 3.92s system 103% cpu 3:18.46 total
```

If however, a pruning phase did occur (perhaps due to a GC), the performance in generating the bitmap would be much faster, as the following shows:

*Running GC*
```
➜  ghs-gym.git git:(master) time jgit gc
Pack refs:              100% (16542/16542)
Counting objects:       497195
Finding sources:        100% (497195/497195)
Getting sizes:          100% (180552/180552)
Writing objects:        100% (497195/497195)
Selecting commits:      153459
Selecting commits:      100% (153459/153459)
Building bitmaps:       100% (30029/30029)
Counting objects:       18465
Finding sources:        100% (18465/18465)
Getting sizes:          100% (8310/8310)
Compressing objects:    100% (1384684/1384684)
Writing objects:        100% (18465/18465)
Prune loose objects also found in pack files: 100% (258/258)
Prune loose, unreferenced objects: 100% (258/258)

jgit gc  236.57s user 7.70s system 103% cpu 3:56.16 total

➜  pack git:(master) ls -1 *.pack | wc -l
       2
➜  pack git:(master) ls -1 *.bitmap | wc -l
       1
```

We now have only two packfiles and one bitmap.

Bitmap Action performance:

```
➜  actions-executor git:(master) ✗ time java -jar target/actions-executor-1.0-SNAPSHOT-jar-with-dependencies.jar BitmapGenerationAction ~/ghs/ghs-gym.git

Counting objects:       497195
Finding sources:        100% (497195/497195)
Getting sizes:          100% (180552/180552)
Writing objects:        100% (497195/497195)
Selecting commits:      153459
Selecting commits:      100% (153459/153459)
Building bitmaps:       100% (30029/30029)

106.76s user 2.45s system 105% cpu 1:43.28 total
```

With the decreased number of packfiles the bitmap generation is much performant.

**Conclusions**

Franco will need to learn that there is a benefit in running bitmap only action, but only when the number of packfiles is low, so that the search for reuse is not too expensive.

In scenarios where the bitmap is missing, *and* the number of packfiles is high, Franco might need to learn to run a GC first.

**Question**: the number of packfiles, is not something that is currently exposed to the model: should that be added so that it could be taken into account when choosing which actions to take, allowing to favour bitmap generation over GC or viceversa?

**Further improvements**

an improvement _could_ be concieved for the Bitmap Action, so that the *biggest packfile with an associated bitmap*  should be scanned first, when searching for object representations. This, as opposed to a blind scan of _all_ packfiles could allow a faster action performance. This would likely need to be a fix in jgit.

@lucamilanesio , @maczech , WDYT?

**Comment by lucamilanesio** [comment] 2024-04-19 15:19
Discussed how to progress on this investigation:
https://drive.google.com/file/d/1BVXywjqruqm9rJxISYMdylJT_0nuW_Cc/view?usp=sharing

**Comment by syntonyze** [comment] 2024-04-23 20:22
Tested a fix where we stop at the first object representation during the search for reuse phase.

Repo:
```
➜  gerrit.INFLATED.4068.packfiles.git git:(master) git count-objects -v
count: 1382
size: 5528
in-pack: 5709430
packs: 4069
size-pack: 3715211
prune-packable: 0
garbage: 0
size-garbage: 0
```

Baseline:

```
➜  actions-executor git:(master) ✗ time java -jar ~/ghs/actions-executor-BASELINE.jar BitmapGenerationAction ~/ghs/gerrit.INFLATED.4068.packfiles.git

Counting objects:       833427
Finding sources:        100% (833427/833427)
Getting sizes:          100% (329477/329477)
Compressing objects:    100% (10679/10679)
Writing objects:        100% (833427/833427)
Selecting commits:      100% (24242/24242)
Building bitmaps:       100% (389/389)

70.95s user 4.76s system 105% cpu 1:11.75 total
```

With fix:

```
Counting objects:       504458
Finding sources:        100% (833427/833427)
Getting sizes:          100% (329505/329505)
Writing objects:        100% (833427/833427)
Selecting commits:      100% (24242/24242)
Building bitmaps:       100% (389/389)

17.43s user 3.33s system 125% cpu 16.521 total
```

A proposal for the fix is here: https://eclipse.gerrithub.io/c/eclipse-jgit/jgit/+/1193535

**Comment by syntonyze** [comment] 2024-05-02 20:15
The relation chain can be found here:

https://review.gerrithub.io/c/GerritForge/gerritforge-health-service/+/1194200

**Comment by syntonyze** [comment] 2024-05-07 13:40
Tests based on: https://review.gerrithub.io/c/GerritForge/gerritforge-health-service/+/1194200

Action:
`time java -jar target/actions-executor-1.0-SNAPSHOT-jar-with-dependencies.jar BitmapGenerationAction ~/ghs/ghs-gym.git`

**Baseline:** 257.12s user 7.13s system 104% cpu **4:13.84 total**
**Change 1194200**: 125.83s user 6.53s system 107% cpu **2:03.40 total**

Resulting packfile size:

**Baseline**
```
-r--r--r--@ 1 syntonyze  staff   307M May  7 15:32 pack-1e968470ef23305960c894379d1702efa9442612.pack
-r--r--r--@ 1 syntonyze  staff    13M May  7 15:32 pack-1e968470ef23305960c894379d1702efa9442612.idx
-r--r--r--@ 1 syntonyze  staff   3.5M May  7 15:32 pack-1e968470ef23305960c894379d1702efa9442612.bitmap
```
**Change 1194200**:

```
-r--r--r--@ 1 syntonyze  staff   342M May  7 15:25 pack-1e968470ef23305960c894379d1702efa9442612.pack
-r--r--r--@ 1 syntonyze  staff    13M May  7 15:25 pack-1e968470ef23305960c894379d1702efa9442612.idx
-r--r--r--@ 1 syntonyze  staff   3.5M May  7 15:26 pack-1e968470ef23305960c894379d1702efa9442612.bitmap
```

**Change 1194200** generates a packfile that is *35Mb* bigger.

This is expected as we are trading off between efficiency and the quality of object representation chosen during the search for reuse

**Comment by DanieleSassoli** [comment] 2024-05-14 13:42
Just to add some stats regarding the target repo we'd like to test against:
- Number of refs: 1413411
- number of refs/heads 909, of which 770 are sandbox
- Number of refs/changes: 1358984,
- Number of changes/meta: 249360
- Number of sandboxes: 1111
- Number of tags: 18594 ( there is no other `refs/builds`, other than `refs/builds/tags`)
- Number of objects and size of repo as shown by `git count-objects -vH`:
```
count: 32
size: 76.00 KiB
in-pack: 27930058
packs: 2
size-pack: 23.81 GiB
prune-packable: 0
garbage: 46
size-garbage: 281.01 GiB 
```

**Comment by syntonyze** [comment] 2024-05-15 12:25
### **Test target ghs-gym**
ghs-gym tarball from review-4 (20240314.144600.ghs-gym.git.tar.gz)

```
➜  pack git:(master) ls -1 *.bitmap | wc -l
       5
➜  pack git:(master) ls -1 *.pack | wc -l
    7731
```

### **Baseline**
Based on gerritforge-health-check [master](https://review.gerrithub.io/plugins/gitiles/GerritForge/gerritforge-health-service/+/38e4f3d53d419d93ae22ba13fb17146018309fb7)

_Total time_: **2:53.21** total
```
➜  actions-executor git:(master) ✗ time java -jar target/actions-executor-1.0-SNAPSHOT-jar-with-dependencies.jar BitmapGenerationAction ~/ghs/ghs-gym.git
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Counting objects:       497195
Finding sources:        100% (497195/497195)
Getting sizes:          100% (180552/180552)
Compressing objects:    100% (4409288/4409288)
Writing objects:        100% (497195/497195)
Selecting commits:      153459
Selecting commits:      100% (153459/153459)
Building bitmaps:       100% (30029/30029)
May 15, 2024 1:52:38 PM com.gerritforge.ghs.actions.Main main
INFO: ActionResult{successful=true, message=}
May 15, 2024 1:52:38 PM com.gerritforge.ghs.actions.Main main
INFO: StatsResult{cpuTime=182144340000, executionTime=173041}
May 15, 2024 1:52:38 PM com.gerritforge.ghs.actions.Main persistExecutionResult
INFO: storing execution results in: /tmp/ghs-action-execution-77040.json
java -jar target/actions-executor-1.0-SNAPSHOT-jar-with-dependencies.jar    176.33s user 5.98s system 105% cpu 2:53.21 total
```

### Jgit improvements
Based on gerritforge-health-check [master](https://review.gerrithub.io/plugins/gitiles/GerritForge/gerritforge-health-service/+/6ccf07f00f3f86670ed922df7c46110875670129)

_Total time_: **38.843** total

```
➜  actions-executor git:(6ccf07f) ✗ time java -jar target/actions-executor-1.0-SNAPSHOT-jar-with-dependencies.jar BitmapGenerationAction ~/ghs/ghs-gym.git
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Counting objects:       497195
Finding sources:        100% (497195/497195)
Getting sizes:          100% (185991/185991)
Compressing objects:    100% (4409288/4409288)
Writing objects:        100% (497195/497195)
Selecting commits:      153459
Selecting commits:      100% (153459/153459)
Building bitmaps:       100% (29971/30029)
May 15, 2024 2:23:14 PM com.gerritforge.ghs.actions.Main main
INFO: ActionResult{successful=true, message=}
May 15, 2024 2:23:14 PM com.gerritforge.ghs.actions.Main main
INFO: StatsResult{cpuTime=63881681000, executionTime=38645}
May 15, 2024 2:23:14 PM com.gerritforge.ghs.actions.Main persistExecutionResult
INFO: storing execution results in: /tmp/ghs-action-execution-79558.json
java -jar target/actions-executor-1.0-SNAPSHOT-jar-with-dependencies.jar    55.81s user 8.25s system 164% cpu 38.843 total
```

**Comment by syntonyze** [comment] 2024-05-15 13:49
# **On ghs-gym host**

### **Test target ghs-gym**
ghs-gym tarball from review-4 (20240314.144600.ghs-gym.git.tar.gz)

```
➜  pack git:(master) ls -1 *.bitmap | wc -l
       5
➜  pack git:(master) ls -1 *.pack | wc -l
    7731
```

### **Baseline**
Based on gerritforge-health-check [master](https://review.gerrithub.io/plugins/gitiles/GerritForge/gerritforge-health-service/+/38e4f3d53d419d93ae22ba13fb17146018309fb7)

_Total time_: **4m 16.203s** total
```
ghs@ghs-gym:~$ time docker run --rm -v /home/ghs/ghs-gym.git:/tmp/ghs-gym.git -v "$PWD/jars":/usr/src/myapp -w /usr/src/myapp openjdk:11 java -jar actions-executor-1.0-SNAPSHOT-BASELINE.jar BitmapGenerationAction /tmp/ghs-gym.git
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Counting objects:       497195
Finding sources:        100% (497195/497195)
Getting sizes:          100% (180552/180552)
Compressing objects:    100% (4409288/4409288)
Writing objects:        100% (497195/497195)
Selecting commits:      153459
Selecting commits:      100% (153459/153459)
Building bitmaps:       100% (30029/30029)
May 15, 2024 1:42:34 PM com.gerritforge.ghs.actions.Main main
INFO: ActionResult{successful=true, message=}
May 15, 2024 1:42:34 PM com.gerritforge.ghs.actions.Main main
INFO: StatsResult{cpuTime=376850000000, executionTime=254587}
May 15, 2024 1:42:34 PM com.gerritforge.ghs.actions.Main persistExecutionResult
INFO: storing execution results in: /tmp/ghs-action-execution-1.json

real	4m16.203s
user	0m0.227s
sys	0m0.180s
```

### Jgit improvements
Based on gerritforge-health-check [master](https://review.gerrithub.io/plugins/gitiles/GerritForge/gerritforge-health-service/+/6ccf07f00f3f86670ed922df7c46110875670129)

_Total time_: **1m 12.423s** total

```
ghs@ghs-gym:~$ time docker run --rm -v /home/ghs/ghs-gym.git:/tmp/ghs-gym.git -v "$PWD/jars":/usr/src/myapp -w /usr/src/myapp openjdk:11 java -jar actions-executor-1.0-SNAPSHOT-jgit-improvements-6ccf07.jar BitmapGenerationAction /tmp/ghs-gym.git
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Counting objects:       497195
Finding sources:        100% (497195/497195)
Getting sizes:          100% (185991/185991)
Compressing objects:    100% (4409288/4409288)
Writing objects:        100% (497195/497195)
Selecting commits:      153459
Selecting commits:      100% (153459/153459)
Building bitmaps:        99% (29771/30029)
May 15, 2024 1:48:25 PM com.gerritforge.ghs.actions.Main main
INFO: ActionResult{successful=true, message=}
May 15, 2024 1:48:25 PM com.gerritforge.ghs.actions.Main main
INFO: StatsResult{cpuTime=483160000000, executionTime=71221}
May 15, 2024 1:48:25 PM com.gerritforge.ghs.actions.Main persistExecutionResult
INFO: storing execution results in: /tmp/ghs-action-execution-1.json

real	1m12.423s
user	0m0.163s
sys	0m0.188s
```

**Comment by syntonyze** [comment] 2024-05-15 16:53
There is an issue whereby when cloning a repository that was targeted by a `BitmapAction` using the improved jgit version as per [this change](https://review.gerrithub.io/c/GerritForge/gerritforge-health-service/+/1194208), an error occurs:

```
ghs@ghs-gym:/tmp$ git clone --no-checkout --no-local ~/ghs-gym.git gh-gym-fast.git
Cloning into 'gh-gym-fast.git'...
remote: warning: ignoring extra bitmap file: ./objects/pack/pack-63bd6faf076d729c5e7aaa625b4dc020781360f2.pack
remote: warning: ignoring extra bitmap file: ./objects/pack/pack-e76b109254205ba13b56d4a09190f4a441abab7a.pack
remote: warning: ignoring extra bitmap file: ./objects/pack/pack-b38451ce94d4b16beca34af703afb84f08320b77.pack
remote: warning: ignoring extra bitmap file: ./objects/pack/pack-ece35923085578199e90fb785fc47583f27476ae.pack
remote: warning: ignoring extra bitmap file: ./objects/pack/pack-2081caaed614588b2b0b144c6f4d18650aff705d.pack
remote: Enumerating objects: 920, done.
remote: Counting objects: 100% (920/920), done.
remote: Compressing objects: 100% (170/170), done.
remote: Total 351838 (delta 797), reused 750 (delta 750), pack-reused 350918
Receiving objects: 100% (351838/351838), 218.69 MiB | 45.55 MiB/s, done.
Resolving deltas: 100% (88396/88396), done.
fatal: did not receive expected object 0300a07e21cb6cdb7df84d5d1f97f64346522b98
fatal: index-pack failed
``` 

Pinpointing the issue by testing against single commits:

97c9d18e3 Introduce `quickMatchSearchForReuse` config - CLONE SUCCESSFUL
e3c581df1 Preload rapid object/pack lookup - CLONE SUCCESSFUL
7b0835149 Leverage preloaded pack index lookup for sizes - CLONE SUCCESSFUL
7e7d04638 Compute bitmaps in parallel slices - CLONE UNSUCCESSFUL

Comparing the output of a successful clone vs the output of an unsuccessful one

Successful run:
```
remote: Enumerating objects: 497195, done.
remote: Total 497195 (delta 0), reused 0 (delta 0), pack-reused 497195
Receiving objects: 100% (497195/497195), 342.04 MiB | 103.62 MiB/s, done.
Resolving deltas: 100% (155141/155141), done.
```

unsuccessful:
```
remote: Enumerating objects: 343283, done.
remote: Counting objects: 100% (924/924), done.
remote: Compressing objects: 100% (174/174), done.
remote: Total 343283 (delta 798), reused 750 (delta 750), pack-reused 342359
Receiving objects: 100% (343283/343283), 211.25 MiB | 101.56 MiB/s, done.
Resolving deltas: 100% (84611/84611), done.
fatal: did not receive expected object 0300a07e21cb6cdb7df84d5d1f97f64346522b98
fatal: fetch-pack: invalid index-pack output
git clone --no-checkout --no-local /Users/syntonyze/ghs/ghs-gym.git   4.67s user 1.89s system 150% cpu 4.356 total
```

Looks like the generated bitmap cannot be used, causing git to count the objects and only finding 924.

**Comment by barbasa** [comment] 2024-05-15 17:10
An extra bit of information. Commit `e3c581df1 Preload rapid object/pack lookup` introduces a regression in the action-executors tests:

```
[INFO] Running com.gerritforge.ghs.actions.PackRefsActionTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.126 s -- in com.gerritforge.ghs.actions.PackRefsActionTest
[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   GarbageCollectionActionTest.applyGarbageCollectionActionShouldRepackRepo:36->GitActionTest.pushNewCommitToBranch:64 » JGitInternal Missing unknown 53c2818605a1547b4991b6f9827f14dbd41f9fce
[INFO]
[ERROR] Tests run: 3, Failures: 0, Errors: 1, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.349 s
[INFO] Finished at: 2024-05-15T19:01:55+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.2.2:test (default-test) on project actions-executor:
[ERROR]
[ERROR] Please refer to /Users/fabioponciroli/Development/gerriforge/gerritforge-health-service/components/actions-executor/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
make: *** [build-jgit-and-executor] Error 1
```

The [jgit build](https://review.gerrithub.io/c/eclipse-jgit/jgit/+/1194530/6) is failing as well.

**Comment by barbasa** [comment] 2024-05-17 15:36
> An extra bit of information. Commit `e3c581df1 Preload rapid object/pack lookup` introduces a regression in the action-executors tests:

This has been fixed by [this commit](https://review.gerrithub.io/c/eclipse-jgit/jgit/+/1194530/5..6).

**Comment by syntonyze** [comment] 2024-05-20 20:28
The chain of optimization changes is finally green: https://eclipse.gerrithub.io/c/eclipse-jgit/jgit/+/1194974

Testing the this chain of changes against the [baseline](https://eclipse.gerrithub.io/plugins/gitiles/eclipse-jgit/jgit/+/a7d0cf38d6d6b6bea5a700d02b4854d687b865ad), we get a considerable improvment in the execution time of the BitmapAction:

**Baseline**:  2:43.86 total
**Optimization**: 36.176 total

These results are based on the `gerrit.INFLATED.4068.packfiles.git` repo that I have uploaded to the ghs-gym environment.

**Comment by lucamilanesio** [comment] 2024-05-21 08:05
@barbasa finalise the Bazel build for building the action executor standalone with JGit improvements.

**Closed** 2024-06-11 10:25 UTC
